version: '3.0'

services:
  redis:
    image: redis
    env_file:
      - ./.env
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A campaign_engine.celery worker --loglevel=INFO
    depends_on:
      - redis
    env_file:
      - ./.env
    
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A campaign_engine.celery beat --loglevel=INFO
    depends_on:
      - redis
    env_file:
      - ./.env

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: