# Generated by Django 5.2.3 on 2025-06-28 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
