# Generated by Django 5.2.3 on 2025-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
